add pprof screens and prometheus metrics
ultracodein/go_core pull request #11
Opened 2020-11-17 00:31 UTC by ultracodein

Для метрик можно было использовать разные типы (gauge и summary тоже подходили для решения задачи). В итоге реализовал те, которые разбирались на лекции.

2020-11-17 05:13 UTC, DmitriyVTitov requested changes
Счётчики неверные.

2020-11-17 05:13 UTC, DmitriyVTitov commented on go_lesson_10/go-core-master/gosearch/pkg/engine/engine.go
> +	Buckets: prometheus.LinearBuckets(0, 1, 50),
первое значение, насколько помню - верхняя граница первой корзинки.
т.е. от -1 до 0 получается, что не логично

2020-11-17 05:13 UTC, DmitriyVTitov commented on go_lesson_10/go-core-master/gosearch/pkg/engine/engine.go
> +	Help:    "Длина поискового запроса, Байт.",
байты с маленькой

2020-11-17 05:13 UTC, DmitriyVTitov commented on go_lesson_10/go-core-master/gosearch/pkg/engine/engine.go
> +	averageQueryLen.Observe((float64(len([]byte(query)))))
[]byte() - лишнее, у строки такая же длина

2020-11-17 05:13 UTC, DmitriyVTitov commented on go_lesson_10/go-core-master/gosearch/pkg/index/hash/hash.go
> +				wordsInIndexTotal.Inc()
это не есть "Количество слов в индексе."
это больше похоже на количество номеров документов. так что счётчик не подходит. не так всё однозначно оказалсь.
сам я не пробовал эти метрики делать, а оно вон как :)

2020-11-17 21:08 UTC, ultracodein commented on go_lesson_10/go-core-master/gosearch/pkg/engine/engine.go
> +	averageQueryLen.Observe((float64(len([]byte(query)))))
Действительно, убрал.

2020-11-17 21:08 UTC, ultracodein commented on go_lesson_10/go-core-master/gosearch/pkg/engine/engine.go
> +	Help:    "Длина поискового запроса, Байт.",
Поправил. Вспомнил, что с большой буквы только в аббревиатурах пишется.

2020-11-17 21:10 UTC, ultracodein commented on go_lesson_10/go-core-master/gosearch/pkg/engine/engine.go
> +	Buckets: prometheus.LinearBuckets(0, 1, 50),
Так и есть, меня смутила реализация:
`
	buckets := make([]float64, count)
	for i := range buckets {
		buckets[i] = start
		start += width
	}
`
- в ней нет ни намека на отрицательные числа. Видимо где-то внутри уже число трактуется как верхняя граница. Поправил.

2020-11-17 22:00 UTC, ultracodein commented on go_lesson_10/go-core-master/gosearch/pkg/index/hash/hash.go
> +				wordsInIndexTotal.Inc()
Точно, поторопился - тут не всегда добавляются новые ключи в словарь. Заменил метрику на Gauge.

2020-11-17 22:07 UTC, ultracodein commented
Внес правки, проверил в отладчике корректность вычисления метрики длины индекса - сейчас все ОК.

2020-11-20 02:56 UTC, DmitriyVTitov approved these changes
ДЗ: в комментария нужно указать запросы для просмотра значений.
Это непосредственно к Go не относится, так что ладно, не придираюсь.

2020-11-22 16:51 UTC, merged