add pkg iface
ultracodein/go_core pull request #12
Opened 2020-11-19 20:21 UTC by ultracodein

Непонятно как в одном пакете сделать 2 разные реализации структур работника/клиента, чтобы они были с одними и теми же именами - поэтому вариант структур с методами назвал `RichEmployee` / `RichCustomer`.

2020-11-22 16:20 UTC, DmitriyVTitov requested changes
Структура проекта неверна.

2020-11-22 16:20 UTC, DmitriyVTitov commented on go_lesson_11/pkg/pure.go
> +package iface
каждый пакет должен быть в своём каталоге.
уже никаких скидок.

2020-11-22 17:11 UTC, ultracodein commented on go_lesson_11/pkg/pure.go
> +package iface
Я "подвис", думая о том, как мне сделать несколько разных реализаций работника/клиента в одном пакете и совсем позабыл об отдельной директории( Исправился.

2020-11-25 08:52 UTC, DmitriyVTitov approved these changes
Хорошо.

2020-11-25 08:52 UTC, DmitriyVTitov commented on go_lesson_11/pkg/iface/pure.go
> +}
без конструкторов тоже можно )

2020-11-25 08:52 UTC, DmitriyVTitov commented on go_lesson_11/pkg/iface/strwriter.go
> +		}
лучше `if str, ok := item.(string); ok { happy_path }`
или `if str, ok := item.(string); !ok { continue }`

2020-11-25 08:52 UTC, DmitriyVTitov commented on go_lesson_11/pkg/iface/strwriter_test.go
> +	if !reflect.DeepEqual(got, want) || gotErr != nil {
сначала лучше проверить ошибку

2020-11-26 21:34 UTC, merged