add server and client
ultracodein/go_core pull request #15
Opened 2020-12-02 23:58 UTC by ultracodein

Пришлось помучиться с клиентом (чтобы он читал только то, что нужно). В итоге реализовал "протокол", в котором сервер отдает на первой строке длину ответа, а на последующих строках - сам ответ (с результатами поиска).

2020-12-05 01:17 UTC, DmitriyVTitov requested changes
Я не приму ваше решение. И вот почему.
1. Я хочу, чтобы вы создали отдельный пакет с сетевой службой и интегрировали его в поисковик. Вместо этого у вас пакет службы подменил сервер. Представьте, что Яндекс так бы решал задачу!
2. Не используйте Read()/Write()! Это очень низкоуровневые штуки, используйте bufio (https://dev-gang.ru/article/golang-prostoy-server-tcp-i-tcp-klient/). И не надо ничего усложнять (придумывать протокол).

2020-12-06 17:03 UTC, DmitriyVTitov commented
Сергей, поскольку я ошибся в формулировке (см. Слак), то можете пересдать это же задание или же исправить - как хотите.

2020-12-07 23:42 UTC, ultracodein commented
Выделил netsrv в отдельный пакет. Все-таки предыдущий вариант с Read/Write и отправкой длины ответа мне нравился больше).

2020-12-11 04:14 UTC, DmitriyVTitov approved these changes
Не увидел интеграции службы в поисковик, но там ничего нового.
Принято!

2020-12-15 21:24 UTC, merged