add client and server for chat task
ultracodein/go_core pull request #19
Opened 2020-12-16 23:31 UTC by ultracodein

2020-12-17 10:13 UTC, DmitriyVTitov requested changes
Не могу принять. Выбранный способ трансляции сообщений всем подключенным клиентам не позволяет масштабировать приложение и является менее логичным и идиоматичным, по сравнению с каналами.

2020-12-17 10:13 UTC, DmitriyVTitov commented on go_lesson_18/websocket/pkg/api/api.go
> +	}
т.е. при получении сообщения вы его добавили в массив - отправили - очистили массив.
я правильно понял?

если так, то это не очень в духе Go. именно этими вещами занимаются каналы.

2020-12-17 10:13 UTC, DmitriyVTitov commented on go_lesson_18/websocket/pkg/api/api.go
> +				api.pool[i].WriteMessage(websocket.TextMessage, []byte(api.messages[j]))
1. не проверяется ошибка
2. отправка сообщений синхронна - для большого количества клиентов тут будет пробка.

использование каналов позволило бы отправлять сообщения асинхронно.

2020-12-18 21:53 UTC, ultracodein commented on go_lesson_18/websocket/pkg/api/api.go
> +	}
Да, все верно, наполняю массив сообщениями, которые успели прилететь, рассылаю их, после чего очищаю массив.

2020-12-18 21:54 UTC, ultracodein commented
Заменил массив с "кешем" сообщений пересылкой между каналами.

2020-12-22 15:18 UTC, DmitriyVTitov approved these changes
OK
кстати, моё решение далеко не идеально. там много "синхронщины" и проблемы с масштабированием

2020-12-22 15:18 UTC, DmitriyVTitov commented on go_lesson_18/websocket/pkg/api/api.go
> +		msgs:     make(chan string),
возможно стоит использовать буферизованный канал
или даже слайс, чтобы клиент не ждал

2020-12-22 15:18 UTC, DmitriyVTitov commented on go_lesson_18/websocket/pkg/api/api.go
> +			ch <- msg
тут возможно стоит сделать `go ... `

2020-12-22 15:18 UTC, DmitriyVTitov commented on go_lesson_18/websocket/pkg/api/api.go
> +			ch <- msg
кроме того, возможна ситуация, когда клиент отключился (уже не читает канал), но канал не успел удалиться, тогда тут будет блокировка навсегда
т.е. нужно здесь тоже блокировать мьютекс перед записью, вроде )

2020-12-22 15:18 UTC, DmitriyVTitov commented on go_lesson_18/websocket/pkg/api/api.go
> +	for msg := range api.msgs {
на мой взгляд эта функция не очень-то принадлежит пакету API

2020-12-22 15:27 UTC, merged