add postgres
ultracodein/go_core pull request #22
Opened 2020-12-26 22:26 UTC by ultracodein

Сложности вызвала работа с SERIAL - оказывается последовательность с автоинкрементом не учитывает уже имеющиеся записи (у меня в тестовой БД 3 фильма и все изменения в тестах я делаю "поверх" этих данных).

В методе добавления массива фильмов реализовал возврат ID добавленных записей - так работать с ним удобнее.

2020-12-27 08:41 UTC, DmitriyVTitov commented
> Сложности вызвала работа с SERIAL - оказывается последовательность с автоинкрементом не учитывает уже имеющиеся записи (у меня в тестовой БД 3 фильма и все изменения в тестах я делаю "поверх" этих данных).

Я об этом говорил на занятии. Посмотрите файл`2-data.sql`: там для этого вызывается перезапуск последовательности со 100. И комментарий есть.

2020-12-27 10:20 UTC, DmitriyVTitov requested changes
1. Контекст используется неверно.
2. Не понял возврат массива ID со 2-го номера. При этом в тесте у вас один фильм добавляется, почему нет паники? Поясните, пожалуйста.
3. Попробуйте решить задачу выдачи фильмов средствами SQL.

2020-12-27 10:20 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	ctx  context.Context
Вот это выглядит странно.
Контекст привязан к конкретному запросу в БД. Он же нужен для отмены запроса в случае, если операция прервалась раньше по цепочке. Например, пользователь веб-приложения закрыл страницу, не дождавшись выполнения операции. Поэтому контекст не может быть одним на всё приложение.
Если он тут чтобы завершить все операции в случае завершения работы, то СУБД сама позаботится о целостности данных. Это ни к чему.

2020-12-27 10:20 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +		db.ctx,
соответственно вот эта строчка выглядит странно, некий общий контекст не имеет смысла

2020-12-27 10:20 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	ids := make([]int, 0)
создаём массив длиной ноль

2020-12-27 10:20 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	return ids[1:], tx.Commit(db.ctx)
возвращаем массив со второго элемента (кстати, почему)

вопрос: а если фильмов было < 2? паника?

2020-12-27 10:20 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	}
такой вариант конструирования запросов неудобен.
попробуйте решить средствами SQL

2020-12-27 10:22 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	for i := 1; i <= len(movies)+1; i++ {
тут у вас тоже почему-то от 1 до len+1, не понятно.
объясните, зачем так

2020-12-27 13:59 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	ctx  context.Context
Да, рассматривал его для общей отмены всех операций. Про отдельные запросы не подумал - сейчас добавил в каждый метод его отдельно.

2020-12-27 13:59 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	ids := make([]int, 0)
Поправил

2020-12-27 14:05 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	return ids[1:], tx.Commit(db.ctx)
```
batch.Queue("SELECT SETVAL('movies_id_seq', (SELECT MAX(id) FROM movies))")
for _, movie := range movies {
    batch.Queue("INSERT INTO movies(...)", ...)
```

У меня в batch помещается запрос на реинициализацию последовательности + N запросов на вставку.
Поэтому первым мне возвращается результат реинициализации (максимальный ID - в моем случае 3 - т.к. в тестовой базе 3 фильма и последний имеет id = 3) и только потом возвращаются id добавленных записей - 4, 5, 6.

Поэтому в массиве всегда будет как минимум 1 элемент или больше. Первый элемент меня не интересует, поэтому я его убираю.

2020-12-27 14:07 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	}
Реализовал функцию на plpgsql с аналогичной логикой.

2020-12-27 14:09 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	for i := 1; i <= len(movies)+1; i++ {
Выше пояснил подробнее - у нас в результатах будет 1 + N записей, в первой итерации считаем MAX(id) - новое стартовое значение для последовательности.

2020-12-27 14:18 UTC, DmitriyVTitov requested changes
Стало в целом хуже :)

2020-12-27 14:18 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	batch.Queue(`SELECT SETVAL('movies_id_seq', (SELECT MAX(id) FROM movies))`)
вот это что-то явно совсем неверное. зачем тогда вообще автоинкремент, если его каждый раз нужно устанавливать вручную?
правильно: вставили записи из скрипта и там же один раз перезапускаете последовательность. пример из занятия:

```
INSERT INTO authors (id, first_name) VALUES (0, 'автор не указан');
-- поскольку id установлен принудительно, то необходимо изменить начало послеовательности
ALTER SEQUENCE authors_id_seq RESTART WITH 100;

```

2020-12-27 14:18 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +
этого тоже быть не должно - источник паники в будущем. уберу я ваш этот первый запрос, как ненужный - и всё.

2020-12-27 14:18 UTC, DmitriyVTitov commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +		`SELECT * FROM select_movies_of_studio($1)`,
прятать логику в СУБД - плохое решение (см. лекцию ещё раз).
придумайте явный способ. нужно всего лишь добавить условие в ваш предыдущий запрос.
подсказка: `WHERE studio_id = $1 OR ...`

2020-12-27 14:18 UTC, DmitriyVTitov commented on go_lesson_21/sql/1-schema.sql
> +$func$ LANGUAGE plpgsql;
то же самое, что и было в Go-функции.
только теперь запрятано в СУБД, где это не прочитать, не протестировать, не отладить (инструментов нет)

2020-12-27 21:53 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +	batch.Queue(`SELECT SETVAL('movies_id_seq', (SELECT MAX(id) FROM movies))`)
Поправил, самого смущало, что его приходится перестанавливать каждый раз.

2020-12-27 21:53 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +
Без первого SELECT - это лишнее, убрал.

2020-12-27 21:54 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +		`SELECT * FROM select_movies_of_studio($1)`,
Спасибо, сделал по наводке, теперь все в одном запросе в скрипте.

2020-12-27 21:55 UTC, ultracodein commented on go_lesson_21/sql/1-schema.sql
> +$func$ LANGUAGE plpgsql;
Функция стала лишней, убрал.

2020-12-28 05:09 UTC, ultracodein commented on go_lesson_21/movies/pkg/storage/postgres/postgres.go
> +			WHERE (SELECT $1) = 0
Да, так проще) Поправил. Почему-то в голову сначала пришло решение с IN - под него и написал условие.

2020-12-28 13:53 UTC, DmitriyVTitov approved these changes
OK

2020-12-28 14:35 UTC, merged