add scheduler
ultracodein/go_core pull request #8
Opened 2020-11-05 23:48 UTC by ultracodein

2020-11-07 15:32 UTC, DmitriyVTitov requested changes
1. не обрабатываются ошибки.
2. логика функций не ясна. имена неудачные.

2020-11-07 15:32 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	}
почему функция печатает сообщение об ошибке?
так обрабатывать ошибки нельзя. ошибку нужно вернуть и как-то на неё отреагировать.
сообщения в консоли сервера никто не видит.

2020-11-07 15:32 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	log.Println("Сохранение данных в кэш.")
вот эти надписи не нужны

2020-11-07 15:32 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +		log.Println(err)
опять сообщение и ничего!

2020-11-07 15:32 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	}()
я не понимаю как синхронизируется работа этих функций.
и почему инициализация в отдельном потоке? я уже это писал, а вы не исправляете.
инициализация должна быть строго "до"! если там много чего происходит, то надо разделить на инициализацию и всё остальное.

2020-11-08 00:17 UTC, ultracodein commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	log.Println("Сохранение данных в кэш.")
Оставил такие надписи только для ошибок и для планировщика.

2020-11-08 00:19 UTC, ultracodein commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	}
Добавил обработку ошибок.

2020-11-08 00:19 UTC, ultracodein commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +		log.Println(err)
Добавил обработку ошибок.

2020-11-08 00:21 UTC, ultracodein commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	}()
Сделал рефакторинг - выделил больше методов и связал их через флаг `started`. Теперь main выглядит понятнее.

2020-11-08 00:21 UTC, ultracodein commented
Сделал рефакторинг. ИМХО стало намного лучше.

2020-11-09 23:10 UTC, DmitriyVTitov approved these changes
Поскольку конкурентное программирование мы ещё не изучали, а другие ваши ошибки прямо к ДЗ не относятся, то принимаю.
Но надо, конечно, больше уделять внимание дизайну кода и, в частности, функций.
Функция должна делать что-то одно.

2020-11-09 23:10 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	}
это точно не Go-way.
вполне ожидал от вас увидеть синхронизацию с помощью канала.

2020-11-09 23:10 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	}
обработка ошибки - задача вызывающего кода.
вызываемый код должен чаще всего просто вернуть эту ошибку.

2020-11-09 23:10 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +// сохраняет обновленные данные и состояние планировщика в файлы
не слишком ли много для одной функции?

2020-11-09 23:10 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +	server.tryInitWithCache()
судя по названию функции, это некая попытка.
при этом функция ничего не возвращает.
как узнать успешность попытки?

2020-11-09 23:10 UTC, DmitriyVTitov commented on go_lesson_07/gosearch/cmd/gosearch/main.go
> +}
опять слишком много всего понамешано.
как такую функцию протестировать? никак!

2020-11-14 14:39 UTC, merged